### ISSUE TITLE
cbauth 4.1.1 package is empty on forgebox

### ISSUE THREAD

**Issue by Skulhammer** [coldbox-modules/cbauth#12]
My coldbox install is pulling the latest cbauth 4.1.1 from https://s3.amazonaws.com/ortus-forgebox-private/elpete/cbauth/4.1.1.zip, but the zip file contains the helper and models folders but no files.

**Comment by elpete** [comment]
Yikes! I ran in to this with another project. It has to do with the gitignore file and the directory the code is in. I’ll have it fixed this morning. For now, pin to the previous version, `4.1.0`. Thanks for letting me know.

**Comment by elpete** [comment]
4.1.2 is out which fixes this issue.  Thanks.
