### ISSUE TITLE
User logged out after 2-4 minutes

### ISSUE THREAD

**Issue by illequipped** [coldbox-modules/cbauth#7]
isloggedin() sets to false after several minutes. It happens regardless of activity or inactivity. The session continues to live on and sessionID remains the same. Tested and confirmed with a simple login app with only Coldbox and cbauth installed through the latest Commandbox running on Lucee 5.2.9.31 as well as the latest Lucee 5.3. No default settings were changed in either Coldbox or Lucee.

**Comment by fiftythreejb** [comment]
I am having exactly the same issue where the session and application (with all variables) persist but the user in cbauth is lost in almost exactly 4 minutes. I am monitoring all my logout events manually and I am getting nothing saying that an event is occurring. It must be something with cbstorages within cbauth?

I am using a more modified version of my login (using cbauth) on the same server in another site and it is working perfectly. 

Coldbox 5.4 | Adobe CF 2016

**Comment by illequipped** [comment]
It should be fixed on the newest version 3.  If i remember the default session storage in the authentication service was originally set to use cachestorage and has been changed to use sessionstorage.

**Comment by elpete** [comment]
Resolved in `v3.0.0`
