### ISSUE TITLE
Interceptor `postAuthentication` and User is Undefined in Arguments

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/cbauth#9]
I am getting an error when trying to use the interceptor `postAuthentication`.  I'd like to reference my User entity and place it in `sessionStorage`.

However, when I test the following interceptor code, I get an error that reads "_Element USER is undefined in ARGUMENTS_":
```
// After a user authenticates, store the user entity in the session (does not work)
function postAuthentication( user, sessionStorage, requestStorage ) {
    arguments.sessionStorage.user = arguments.user;
}
```
I am authenticating in my handler with the following code:
```
auth().authenticate( rc.emailAddress, rc.userPassword );
```

Ultimately what I'm trying to do is store some frequently accessed data (like the logged in user's first name and avatar) in the session scope so I don't have to go to the database on every page request.  Finally, I'd like to be able to update the session data in case the user ever changes their name or something. [I also asked a new StackOverflow question on the subject](https://stackoverflow.com/questions/57897412/how-to-i-store-retrieve-and-update-session-user-data-using-cbauth-in-a-coldbox).

Thanks for all your contributions on Forgebox by the way!

**Comment by elpete** [comment]
The data you are trying to reference is inside the `interceptData` struct.  The method signature of any interceptor is as follows:

```
function interceptorName( required struct interceptData, required buffer, event, rc, prc );
```

So you would access user as `arguments.interceptData.user` and store it using `arguments.sessionStorage.setVar( "user", arguments.interceptData.user );`  (`sessionStorage` is not the `session` scope.  It is a facade provided by [`cbstorages`](https://github.com/coldbox-modules/cbstorages/blob/v1.5.0/models/SessionStorage.cfc).
